"""add content-html field to post model

Revision ID: 98a34b4de711
Revises: 8675f94fd3f1
Create Date: 2016-07-06 12:16:21.544961

"""

# revision identifiers, used by Alembic.
revision = '98a34b4de711'
down_revision = '8675f94fd3f1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'content_html')
    ### end Alembic commands ###
